#!/bin/sh
cd src
./cleanup
cd ..
rm -f srcbin.tar extgraph.zip extgraph.tar extgraph.tar.bz2
tar -cf srcbin.tar --owner=0 src bin --exclude=.svn --exclude=*.dbg
zip -r -q -9 extgraph.zip BIN89 BIN92PV200 DOCS lib srcbin.tar LICENSE.txt README.txt LGPL.txt todo\ extgraph.txt makedist -x \*.svn -x \*.dbg
rm -f srcbin.tar
tar -cf extgraph.tar --owner=0 bin BIN89 BIN92PV200 DOCS lib src LICENSE.txt README.txt LGPL.txt todo\ extgraph.txt makedist --exclude=.svn --exclude=*.dbg
bzip2 --best extgraph.tar
