#!/bin/sh
tigcc -O3 -Wall -W -fomit-frame-pointer -Wwrite-strings -mpcrel -mregparm=5 -ffunction-sections -fdata-sections --optimize-code --cut-ranges --reorder-sections -mno-bss -Wa,-l -Wa,--all-relocs -WA,-a -DUSE_TI89 -DUSE_TI92P -DUSE_V200 $1.c ../../lib/extgraph.a ../../lib/tilemap.a $2
mv $1.89z ../../BIN89
mv $1.9xz ../../BIN92PV200
mv $1.v2z ../../BIN92PV200
