#!/bin/sh
echo ======= building demos =======
./buildsep demo1
./buildcmp demo2
./buildcmp demo3
./buildcmp demo4
./buildcmp demo5
echo demo6
./buildsep demo6
./buildcmp demo7
./buildcmp demo8
./buildcmp demo9
./buildcmp demo10
./buildsep demo11
echo demo12
./buildsep demo12 ../../lib/gray.o
./buildsep demo13 ../../lib/gray.o
./buildsep demo14 ../../lib/gray.o
echo demo15
./buildsep demo15 ../../lib/gray.o
./buildsep demo16 ../../lib/gray.o
./buildsep demo17 ../../lib/gray.o
echo demo18
./buildcmp demo18
./buildcmp demo19 ../../lib/gray.o
./buildcmp demo20
./buildcmp demo21
./buildsep demo22 ../../lib/gray.o
echo demo24
./buildsep demo24 ../../lib/gray.o
./buildsep demo25 ../../lib/gray.o
tigcc demo26.asm ../../lib/extgraph.a ../../lib/tilemap.a ../../lib/gray.o
mv demo26.89z ../../BIN89
mv demo26.9xz ../../BIN92PV200
mv demo26.v2z ../../BIN92PV200
./buildcmp demo27
./buildsep demo28
./buildsep demo29
./buildcmp demo30
./buildsep demo31
./buildcmp demo32
